package com.pulmuone.mrtina.popupSubInv;

import java.io.Serializable;

public class PopSubInvItem implements Serializable {
	public String  SUBINVENTORY_CODE,
					SUBINVENTORY_NAME,
					ORG_ID,
					LOCATOR_CONTROL,
					PALLET_CONTROL,
					LOC_PO_RCV_ID,
					LOC_PO_RCV_CODE,
					LOC_TRO_RCV_ID,
					LOC_TRO_RCV_CODE,
					LOC_SUBINV_TRSF_ID,
					LOC_SUBINV_TRSF_CODE,
					LOC_TRO_TRSF_ID,
					LOC_TRO_TRSF_CODE,
					LOC_BATCH_TXN_ID,
					LOC_BATCH_TXN_CODE,
					LOC_STAGE_TXN_ID,
					LOC_STAGE_TXN_CODE;

	public PopSubInvItem(String SUBINVENTORY_CODE, String SUBINVENTORY_NAME, String ORG_ID, String LOCATOR_CONTROL,
						 String PALLET_CONTROL, String LOC_PO_RCV_ID, String LOC_PO_RCV_CODE, String LOC_TRO_RCV_ID,
						 String LOC_TRO_RCV_CODE, String LOC_SUBINV_TRSF_ID, String LOC_SUBINV_TRSF_CODE, String LOC_TRO_TRSF_ID,
						 String LOC_TRO_TRSF_CODE, String LOC_BATCH_TXN_ID, String LOC_BATCH_TXN_CODE, String LOC_STAGE_TXN_ID, String LOC_STAGE_TXN_CODE) {
		this.SUBINVENTORY_CODE = SUBINVENTORY_CODE;
		this.SUBINVENTORY_NAME = SUBINVENTORY_NAME;
		this.ORG_ID = ORG_ID;
		this.LOCATOR_CONTROL = LOCATOR_CONTROL;
		this.PALLET_CONTROL = PALLET_CONTROL;
		this.LOC_PO_RCV_ID = LOC_PO_RCV_ID;
		this.LOC_PO_RCV_CODE = LOC_PO_RCV_CODE;
		this.LOC_TRO_RCV_ID = LOC_TRO_RCV_ID;
		this.LOC_TRO_RCV_CODE = LOC_TRO_RCV_CODE;
		this.LOC_SUBINV_TRSF_ID = LOC_SUBINV_TRSF_ID;
		this.LOC_SUBINV_TRSF_CODE = LOC_SUBINV_TRSF_CODE;
		this.LOC_TRO_TRSF_ID = LOC_TRO_TRSF_ID;
		this.LOC_TRO_TRSF_CODE = LOC_TRO_TRSF_CODE;
		this.LOC_BATCH_TXN_ID = LOC_BATCH_TXN_ID;
		this.LOC_BATCH_TXN_CODE = LOC_BATCH_TXN_CODE;
		this.LOC_STAGE_TXN_ID = LOC_STAGE_TXN_ID;
		this.LOC_STAGE_TXN_CODE = LOC_STAGE_TXN_CODE;
	}
}