package com.pulmuone.mrtina.popupTranPall;

import java.io.Serializable;

public class PopTranPallItem implements Serializable {
	public String  ORGANIZATION_CODE,
			PRIMARY_UOM_CODE,
			SUBINVENTORY_CODE,
			LOCATOR_CODE,
			ITEM_DESC,
			ITEM_CODE,
			ORGANIZATION_ID,
			LOCATOR_NAME,
			PRIMARY_QUANTITY,
			OU_ID,
			PALLET_ID,
			INVENTORY_LOCATION_ID,
			PALLET_NUMBER,
			LOCATOR_CONTROL,
			LOT_NUMBER,
			TRSF_SUBINVENTORY_CODE,
			TRSF_INV_LOCATION_ID,
			TRSF_LOCATOR_CODE;

	public PopTranPallItem(String ORGANIZATION_CODE, String PRIMARY_UOM_CODE, String SUBINVENTORY_CODE, String LOCATOR_CODE,
						   String ITEM_DESC, String ITEM_CODE, String ORGANIZATION_ID, String LOCATOR_NAME, String PRIMARY_QUANTITY,
						   String OU_ID, String PALLET_ID, String INVENTORY_LOCATION_ID, String PALLET_NUMBER, String LOCATOR_CONTROL,
						   String LOT_NUMBER, String TRSF_SUBINVENTORY_CODE, String TRSF_INV_LOCATION_ID, String TRSF_LOCATOR_CODE) {
		this.ORGANIZATION_CODE = ORGANIZATION_CODE;
		this.PRIMARY_UOM_CODE = PRIMARY_UOM_CODE;
		this.SUBINVENTORY_CODE = SUBINVENTORY_CODE;
		this.LOCATOR_CODE = LOCATOR_CODE;
		this.ITEM_DESC = ITEM_DESC;
		this.ITEM_CODE = ITEM_CODE;
		this.ORGANIZATION_ID = ORGANIZATION_ID;
		this.LOCATOR_NAME = LOCATOR_NAME;
		this.PRIMARY_QUANTITY = PRIMARY_QUANTITY;
		this.OU_ID = OU_ID;
		this.PALLET_ID = PALLET_ID;
		this.INVENTORY_LOCATION_ID = INVENTORY_LOCATION_ID;
		this.PALLET_NUMBER = PALLET_NUMBER;
		this.LOCATOR_CONTROL = LOCATOR_CONTROL;
		this.LOT_NUMBER = LOT_NUMBER;
		this.TRSF_SUBINVENTORY_CODE = TRSF_SUBINVENTORY_CODE;
		this.TRSF_INV_LOCATION_ID = TRSF_INV_LOCATION_ID;
		this.TRSF_LOCATOR_CODE = TRSF_LOCATOR_CODE;

	}

}